# Site settings
title: Kirill Sevriugin
description: DevOps Engineer
about: "I am a highly skilled DevOps engineer with more than 6 years of experience. My job is my hobby, and I am very passionate about it. I love, believe and participate in OpenSource. I have much experience as a Senior DevOps engineer."
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://kisev.me"

# User settings
username: Kirill Sevriugin
user_description: kisev
user_title: DevOps Engineer
email: kisevme@gmail.com
github: kisev
linkedin: kisev
skype: live:kirillsev
telegram: kisev

# Google-analytics
google-analytics:
  id: "UA-117622777-1"

yandex-metrika:
  id: "44699182"

exclude: ['package.json', 'src' , 'node_modules']
