# Site settings
title: Kirill Sevriugin
description: DevOps Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kirill Sevriugin
user_description: kisev
user_title: DevOps Engineer
email: kisevme@gmail.com
twitter_username: kisev
github_username: kisev
gplus_username: kisev

# Google-analytics
google-analytics:
  id: ""

yandex-metrika:
  id: "44699182"

exclude: ['package.json', 'src' , 'node_modules']
